export const COOKIE_MAX_AGE = 60 * 60 * 12;
export const POSITION_COOKIE_KEY = "user_position_id";

export const POSITION = {
  REGULAR_FIREFIGHTER: 1,
  OIC: 2,
  OFFICER: 3,
  CADET: 4,
} as const;

export const PERMISSION = {
  ALL: [
    POSITION.REGULAR_FIREFIGHTER,
    POSITION.OIC,
    POSITION.OFFICER,
    POSITION.CADET,
  ],
  REGULARS: [POSITION.REGULAR_FIREFIGHTER, POSITION.OIC, POSITION.OFFICER],
  OIC_AND_OFFICER: [POSITION.OIC, POSITION.OFFICER],
  OFFICER_ONLY: [POSITION.OFFICER],
} as const;
